apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: soil-app
spec:
  type: LoadBalancer 
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8080      
    targetPort: 80