apiVersion: batch/v1
kind: Job
metadata:
  name: data-processing-job
  namespace: student-project
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: processor
        image: busybox
        command: 
         - sh
         - -c
         - |
           echo "Starting data processing job";
           sleep 5;
           echo "Data processing job completed";
      restartPolicy: Never


# kubectl apply -f job/one-time-job.yaml
# kubectl get job -n student-project 
#kubectl get pods -n student-project 
#kubetcl logs <pod-name> -n student-project 